# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('para_A', models.IntegerField()),
                ('para_B', models.IntegerField()),
                ('para_C', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=200)),
                ('answer', models.ManyToManyField(to='general.Answer', verbose_name='list of answer')),
            ],
        ),
    ]
